name: Report a bug with Proxmox VE Custom Integration
description: Report a bug with Proxmox VE Custom Integration
labels: bug
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: Please verify that you've followed these steps
      options:
        - label: I have updated to the latest available Proxmox VE Custom Integration version.
          required: true
  - type: markdown
    attributes:
      value: |
        ## The problem
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the issue you are experiencing
      description: Provide a clear and concise description of what the bug is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    validations:
      required: true
    attributes:
      label: In which version of Home Assistant Core do you have the problem?
      placeholder: core-
      description: >
        Can be found in: [Settings -> About](https://my.home-assistant.io/redirect/info/).
  - type: input
    validations:
      required: true
    attributes:
      label: What version of Proxmox VE Custom Integration has the issue?
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
